version: 1
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2

    steps:
      - run:
          name: Test
          command: npm run test
          
      - run:
          name: Build
          command: npm run build

