version: 1
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - run:
          name: Test
          command: npm run test
          
      - run:
          name: Build
          command: npm run build

